spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:service}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admins}
#    virtual-host: my_vhost
  redis:
    host: ${REDIS_HOST:service}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
    password: ${REDIS_PASSWORD:admins}
    database: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:service}:${DATASOURCE_PORT:3358}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
#  resources:
#    add-mappings: false

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.chauncy.cloud
  local:
    # 默认2小时本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 3600000
      expireAfterAccessInMillis: 1800000
    # 長時本地緩存，主要用于要求时效一般
    longTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
      expireAfterAccessInMillis: 180000
    # 短時本地緩存，主要用于要求时效较高的配置
    shortTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000
  remote:
    # 默认1小时的远程缓存
    default:
      type: redis
      expireAfterWriteInMillis: 360000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:service}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admins}
      database: 1
    # 长时远程緩存，主要用于要求时效要求一般的集中式缓存
    longTime:
      type: redis
      expireAfterWriteInMillis: 7200000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:service}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admins}
      database: 1
    # 短時远程緩存，主要用于要求时效较高的集中式缓存
    shortTime:
      type: redis
      expireAfterWriteInMillis: 300000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:service}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admins}
      database: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug
    com.chauncy.cloud: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
  path: logs/
  file:
    max-size: 1GB
  config: classpath:worker_logback.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)

master.exec.threads: 100

# master execute task number in parallel
master.exec.task.num: 20

# master heartbeat interval
master.heartbeat.interval: 10

# master commit task retry times
master.task.commit.retryTimes: 5

# master commit task interval
master.task.commit.interval: 1000


# only less than cpu avg load, master server can work. default value : the number of cpu cores * 2
master.max.cpuload.avg: 100

# only larger than reserved memory, master server can work. default value : physical memory * 1/10, unit is G.
master.reserved.memory: 0.1

# worker settings
# worker execute thread num
worker.exec.threads: 100

# worker heartbeat interval
worker.heartbeat.interval: 10

# submit the number of tasks at a time
worker.fetch.task.num :  3

# only less than cpu avg load, worker server can work. default value : the number of cpu cores * 2
worker.max.cpuload.avg: 100

# only larger than reserved memory, worker server can work. default value : physical memory * 1/6, unit is G.
worker.reserved.memory: 0.1
