server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:service}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:service}:${REGISTER_PORT:8848}
        file-extension: yml
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:service}:${SENTINEL_DASHBOARD_PORT:8021}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:service}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admins}
    redis:
      host: ${REDIS_HOST:service}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admins}
      lettuce:
        pool:
          max-active: 300

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:serrvice}:${DATASOURCE_PORT:3358}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}