spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:service}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admins}
    virtual-host: my_vhost
  redis:
    host: ${REDIS_HOST:service}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
    password: ${REDIS_PASSWORD:admins}
    database: 1

  datasource:
    druid:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:service}:${DATASOURCE_PORT:3358}/sc_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
        username: ${DATASOURCE_USERNAME:root}
        password: ${DATASOURCE_PASSWORD:root123}
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #Oracle需要打开注释
        #validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: false
          wall:
            config:
              multi-statement-allow: true
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:service}:${DATASOURCE_PORT:3358}/chauncy-cloud2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
        username: ${DATASOURCE_USERNAME:root}
        password: ${DATASOURCE_PASSWORD:root123}
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #Oracle需要打开注释
        #validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: false
          wall:
            config:
              multi-statement-allow: true

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    loadbalancer:
      retry:
        enabled: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
    com.chauncy.cloud: debug
  path: logs/
  file:
    max-size: 1GB

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true

##设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
##指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout: 50000
##指的是建立事件后从服务器读取到可用资源所用资源的时间
#  ConnectTimeout: 50000